spin_manifest_version = 2

[application]
name = "Go Azure"
version = "0.1.0"
authors = ["Andrew Steurer <andrew.steurer@fermyon.com>"]

[variables]
az_account_name = { required = true, secret = true }
az_shared_key = { required = true, secret = true }


[[trigger.http]]
route = "/..."
component = "go-azure"

[component.go-azure]
source = "main.wasm"
# If the app needs to access multiple storage accounts, use "https://*.{{blob|queue}}.core.windows.net"
allowed_outbound_hosts = [
    "https://{{ az_account_name }}.blob.core.windows.net", 
    "https://{{ az_account_name }}.queue.core.windows.net",
]

[component.go-azure.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]

[component.go-azure.variables]
az_account_name = "{{ az_account_name }}"
az_shared_key = "{{ az_shared_key }}"